routes/web.php
<?php

use App\Http\Controllers\AccessoryController;
use App\Http\Controllers\ActiveLogController;
use App\Http\Controllers\AssetController;
use App\Http\Controllers\AssetModelController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ComponentController;
use App\Http\Controllers\CustomFieldController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\LicenseController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\TableController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MediaController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('dashboard',[DashboardController::class,'index'])->name('dashboard.index');
Route::get('/',[DashboardController::class,'index']);

Route::get('/medias',[MediaController::class,'index'])->name('medias.index');
Route::get('get-data/medias/{id}',[MediaController::class,'getData'])->name('medias.data');
Route::post('post-data/medias/{id}',[MediaController::class,'uploadFile'])->name('medias.upload');
Route::post('medias-folder/store',[MediaController::class,'storeFolder'])->name('medias.folder.store');
Route::post('/medias-rename/update',[MediaController::class,'renameMedia'])->name('medias.rename');
Route::post('/medias-move/trash',[MediaController::class,'moveTrashMedia'])->name('medias.move.trash');
Route::get('/medias/download/{id}',[MediaController::class,'downloadMedia'])->name('medias.download');
Route::post('/medias/delete',[MediaController::class,'deleteMedia'])->name('medias.delete');
Route::post('/medias/restore',[MediaController::class,'restoreMedia'])->name('medias.restore');


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group( ['prefix'=>'users','as'=>'users.'],function () {
    Route::get('/',[UserController::class,'index'])->name('index');
    Route::get('/list/{trash}',[UserController::class,'index'])->name('trash');
    Route::get('/create',[UserController::class,'create'])->name('create');
    Route::post('/store',[UserController::class,'store'])->name('store');
    Route::get('/edit/{id}',[UserController::class,'edit'])->name('edit');
    Route::post('/update/{id}',[UserController::class,'update'])->name('update');
    Route::get('/clone/{id}',[UserController::class,'clone'])->name('clone');

    Route::delete('/deletes',[UserController::class,'deletes'])->name('deletes');
    Route::delete('/deleted/{id}',[UserController::class,'deleted'])->name('deleted');
    Route::delete('/empty-trash',[UserController::class,'emptyAllTrash'])->name('empty_trash');
    Route::get('/restore/{id}',[UserController::class,'restore'])->name('restore');
    Route::delete('/destroy/{id}',[UserController::class,'destroy'])->name('destroy');
    Route::get('{id}',[UserController::class,'show'])->name('show');
    Route::get('accessories/{id}',[UserController::class,'accessory'])->name('accessories');
    Route::get('assets/{id}',[UserController::class,'asset'])->name('assets');
});

Route::group( ['prefix'=>'companies','as'=>'companies.'],function () {
    Route::prefix('companies')->group(function () {
        Route::get('/',[CompanyController::class,'index'])->name('index');
        Route::get('/create',[CompanyController::class,'create'])->name('create');
        Route::post('/store',[CompanyController::class,'store'])->name('store');
        Route::get('/edit/{id}',[CompanyController::class,'edit'])->name('edit');
        Route::post('/update/{id}',[CompanyController::class,'update'])->name('update');
        Route::delete('/deletes/{id}',[CompanyController::class,'destroy'])->name('destroy');
    });
});
Route::prefix('departments')->group(function () {
    Route::get('/',[DepartmentController::class,'index'])->name('departments.index');
    Route::get('/create',[DepartmentController::class,'create'])->name('departments.create');
    Route::post('/store',[DepartmentController::class,'store'])->name('departments.store');
    Route::get('/edit/{id}',[DepartmentController::class,'edit'])->name('departments.edit');
    Route::post('/update/{id}',[DepartmentController::class,'update'])->name('departments.update');
    Route::delete('/deletes/{id}',[DepartmentController::class,'destroy'])->name('departments.destroy');

});

Route::prefix('categories')->group(function () {
    Route::get('/',[CategoryController::class,'index'])->name('categories.index');
    Route::get('/create',[CategoryController::class,'create'])->name('categories.create');
    Route::post('/store',[CategoryController::class,'store'])->name('categories.store');
    Route::get('/edit/{id}',[CategoryController::class,'edit'])->name('categories.edit');
    Route::post('/update/{id}',[CategoryController::class,'update'])->name('categories.update');
    Route::delete('/deletes/{id}',[CategoryController::class,'destroy'])->name('categories.destroy');
    Route::get('{id}',[CategoryController::class,'show'])->name('categories.show');
});
Route::prefix('locations')->group(function () {
    Route::get('/',[LocationController::class,'index'])->name('locations.index');
    Route::get('/create',[LocationController::class,'create'])->name('locations.create');
    Route::post('/store',[LocationController::class,'store'])->name('locations.store');
    Route::get('/edit/{id}',[LocationController::class,'edit'])->name('locations.edit');
    Route::post('/update/{id}',[LocationController::class,'update'])->name('locations.update');
    Route::delete('/deletes/{id}',[LocationController::class,'destroy'])->name('locations.destroy');
    Route::get('{id}',[LocationController::class,'show'])->name('locations.show');
});

Route::prefix('components')->group(function () {
    Route::get('/',[ComponentController::class,'index'])->name('components.index');
    Route::get('/create',[ComponentController::class,'create'])->name('components.create');
    Route::post('/store',[ComponentController::class,'store'])->name('components.store');
    Route::get('/edit/{id}',[ComponentController::class,'edit'])->name('components.edit');
    Route::post('/update/{id}',[ComponentController::class,'update'])->name('components.update');
    Route::delete('/deletes/{id}',[ComponentController::class,'destroy'])->name('components.destroy');
    Route::get('{id}',[ComponentController::class,'show'])->name('components.show');
    Route::post('{id}/checkout',[ComponentController::class,'checkout'])->name('components.checkout');
    Route::post('{id}/checkin',[ComponentController::class,'checkin'])->name('components.checkin');
    Route::get('/{id}/qr-code-download',[ComponentController::class,'qrCodeDownload'])->name('components.qr.download');
});

Route::prefix('licenses')->group(function () {
    Route::get('/',[LicenseController::class,'index'])->name('licenses.index');
    Route::get('/list/{trash}',[LicenseController::class,'index'])->name('licenses.trash');
    Route::get('/create',[LicenseController::class,'create'])->name('licenses.create');
    Route::post('/store',[LicenseController::class,'store'])->name('licenses.store');
    Route::get('/edit/{id}',[LicenseController::class,'edit'])->name('licenses.edit');
    Route::post('/update/{id}',[LicenseController::class,'update'])->name('licenses.update');
    Route::get('/clone/{id}',[LicenseController::class,'clone'])->name('licenses.clone');
    Route::delete('/deletes/{id}',[LicenseController::class,'destroy'])->name('licenses.destroy');

    Route::post('{id}/checkout/{seat_id?}',[LicenseController::class,'checkout'])->name('licenses.checkout');
    Route::post('{id}/checkin/{seat_id?}',[LicenseController::class,'checkin'])->name('licenses.checkin');
    Route::get('/{id}',[LicenseController::class,'show'])->name('licenses.show');
    Route::get('/{id}/qr-code-download',[LicenseController::class,'qrCodeDownload'])->name('licenses.qr.download');
});

Route::prefix('accessories')->group(function () {
    Route::get('/',[AccessoryController::class,'index'])->name('accessories.index');
    Route::get('/list/{trash}',[AccessoryController::class,'index'])->name('accessories.trash');
    Route::get('/create',[AccessoryController::class,'create'])->name('accessories.create');
    Route::post('/store',[AccessoryController::class,'store'])->name('accessories.store');
    Route::get('/edit/{id}',[AccessoryController::class,'edit'])->name('accessories.edit');
    Route::post('/update/{id}',[AccessoryController::class,'update'])->name('accessories.update');
    Route::get('/clone/{id}',[AccessoryController::class,'clone'])->name('accessories.clone');

    Route::delete('/deletes',[AccessoryController::class,'deletes'])->name('accessories.deletes');
    Route::delete('/deleted/{id}',[AccessoryController::class,'deleted'])->name('accessories.deleted');
    Route::delete('/empty-trash',[AccessoryController::class,'emptyAllTrash'])->name('accessories.empty_trash');
    Route::get('/restore/{id}',[AccessoryController::class,'restore'])->name('accessories.restore');
    Route::delete('/destroy/{id}',[AccessoryController::class,'destroy'])->name('accessories.destroy');
    Route::post('{id}/checkout/{seat_id?}',[AccessoryController::class,'checkout'])->name('accessories.checkout');
    Route::post('{id}/checkin/{seat_id?}',[AccessoryController::class,'checkin'])->name('accessories.checkin');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Gate;

class Company extends Model
{
    use HasFactory;

    protected $table = 'companies';
    protected $fillable = ['name', 'image'];

    public function users()
    {
        return $this->hasMany(User::class, 'company_id');
    }

    public function isDeletable()
    {
        if (($this->assets()->count() === 0)
            && ($this->accessories()->count() === 0)
            && ($this->components()->count() === 0)
            && ($this->users()->count() === 0)) {
            return false;
        }
        return true;

    }


    public function assets()
    {
        return $this->hasMany(Asset::class, 'company_id');
    }

    public function licenses()
    {
        return $this->hasMany(License::class, 'company_id');
    }

    public function accessories()
    {
        return $this->hasMany(Accessory::class, 'company_id');
    }

    public function components()
    {
        return $this->hasMany(Component::class, 'company_id');
    }
}

app/Http/Controllers/Api/CompanyController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Company;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;

class CompanyController extends Controller
{

    public function index(Request $request)
    {

        if ($request->ajax()) {

            $term = trim($request->term);
            $posts = Company::select('id', 'name as text')
                ->where('name', 'LIKE', '%' . $term . '%')
                ->orderBy('name', 'asc')->simplePaginate(2);

            $morePages = true;
            if (empty($posts->nextPageUrl())) {
                $morePages = false;
            }
            $results = array(
                "results" => $posts->items(),
                "pagination" => array(
                    "more" => $morePages
                )
            );

            return response()->json($results);
        }

    }


}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Events\CreatedContentEvent;
use App\Http\Responses\BaseHttpResponse;
use App\Models\Company;
use App\TableList\CompanyTable;
use Illuminate\Http\Request;

class CompanyController extends Controller
{

    protected $response;

    public function __construct(BaseHttpResponse $response)
    {
        $this->response = $response;
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Support\Facades\View|BaseHttpResponse
     * @throws \Throwable
     */
    public function index(CompanyTable $dataTable,Request $request)
    {
        if (!$request->user()->can('view-company')) {
            return $this->response
                ->setError()
                ->setNextUrl(redirect()->back()->getTargetUrl())
                ->setMessage(trans('table.no_permission'));
        }
        page_title()->setTitle(trans('layout.companies'));
        return $dataTable->renderTable();
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Contracts\View\View|BaseHttpResponse
     */
    public function create(Request $request)
    {
        if (!$request->user()->can('create-company')) {
            return $this->response
                ->setError()
                ->setNextUrl(redirect()->back()->getTargetUrl())
                ->setMessage(trans('table.no_permission'));
        }
        page_title()->setTitle(trans('layout.company.create'));
        return view('companies.add');
    }

    /**
     * Store a newly created resource in storage.
     * @param \Illuminate\Http\Request $request
     * @return BaseHttpResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|min:1|max:255|unique:companies,name'
        ]);

        try {
            $company = new Company();
            $company->create([
                'name' => $request->name,
                'image' => $request->image
            ]);
            event(new CreatedContentEvent($request->all(), $company, config('general.log.create')));
            return $this->response
                ->setPreviousUrl(route('companies.index'))
                ->setMessage(trans('table.create_success_message'));
        } catch (Exception $exception) {
            return $this->response
                ->setError()
                ->setMessage('Errors exception');
        }
    }

    /**
     * Display the specified resource.
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return \Illuminate\Contracts\View\View|BaseHttpResponse
     */
    public function edit($id,Request $request)
    {
        if (!$request->user()->can('edit-company')) {
            return $this->response
                ->setError()
                ->setNextUrl(redirect()->back()->getTargetUrl())
                ->setMessage(trans('table.no_permission'));
        }
        page_title()->setTitle(trans('layout.company.edit'));
        $company = Company::find($id);
        return view('companies.edit', ['company' => $company]);
    }

    /**
     * Update the specified resource in storage.
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return BaseHttpResponse
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|min:1|max:255|unique:companies,name' . $id,
        ]);
        try {
            $company = Company::find($id);
            $company->update([
                'name' => $request->name,
                'image' => $request->image
            ]);
            event(new CreatedContentEvent($request->all(), $company, config('general.log.update')));
            return $this->response
                ->setPreviousUrl(route('companies.index'))
                ->setMessage(trans('table.create_success_message'));
        } catch (Exception $exception) {
            return $this->response
                ->setError()
                ->setMessage($exception->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return BaseHttpResponse
     */
    public function destroy($id,Request $request)
    {
        try {
            if (!$request->user()->can('delete-company')) {
                return $this->response
                    ->setError()
                    ->setNextUrl(redirect()->back()->getTargetUrl())
                    ->setMessage(trans('table.no_permission'));
            }
            $company = Company::find($id);
            $company->delete();
            event(new CreatedContentEvent($id, $company, config('general.log.destroy')));
            return $this->response->setMessage(trans('table.delete_success_message'));
        } catch (Exception $exception) {
            return $this->response
                ->setError()
                ->setMessage($exception->getMessage());
        }
    }
}

resources/views/companies/add.blade.php
@extends('layouts.app')
@section('content')
    <div class=" rv-media-integrate-wrapper ">
        {{ Breadcrumbs::render('companies.add') }}
        <div id="main" class="container">
            <form method="POST" action="{{route( 'companies.store')}}" accept-charset="UTF-8">
                @csrf
                <div class="row">
                    <div class="col-md-12 ">
                        <div class="main-form content-page">
                            <div class="form-body">
                                <div class="form-group row">
                                    <div class="col-2"> <label for="name" class="text-title-field control-label required">
                                        {{trans('layout.name')}}</label>
                                    </div>
                                    <div class="col-10">
                                        <input class="form-control @error('name') is-invalid @enderror"
                                             name="name" type="text" id="first_name" value="{{old('name')}}">
                                        @error('name')
                                        <span class="text-danger">{{ $message }}</span>
                                        @enderror
                                    </div>

                                </div>
                                <div class="form-group row">
                                    <div class="col-2">
                                        <label for="name" class="text-title-field control-label ">{{trans('layout.image')}}</label>
                                    </div>
                                    <div class="col-10">
                                        <!-- Button trigger modal -->
                                        <div class="image-box image">
                                            <input type="hidden" name="image" value="{{old('image')}}" class="image-data">
                                            <div class="preview-image-wrapper " style="">
                                                <img src="{{asset('images/placeholder.png')}}" alt="Preview image"
                                                     class="preview_image" width="150">
                                                <a class="btn_remove_image" title="Remove image">
                                                    <i class="fa fa-times"></i>
                                                </a>
                                            </div>
                                            <div class="image-box-actions">
                                                <a href="#" class="btn_gallery" data-result="image" data-bs-toggle="modal"
                                                   data-bs-target="#exampleModal">
                                                    {{trans('layout.choose_image')}}
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="widget meta-boxes d-flex justify-content-center">
                                <div class="widget-body">
                                    <div class="btn-set">
                                        <a  href="{{route('companies.index')}}" class="float-left btn btn-warning mr-5"> {{trans('layout.cancel')}}</a>
                                        <button type="submit" name="submit" value="save" class="btn btn-info">
                                            <i class="fa fa-save"></i>  {{trans('layout.save')}}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </form>
        </div>
    </div>
    @include('partials.media')

@stop

resources/views/companies/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class=" rv-media-integrate-wrapper">
        {{ Breadcrumbs::render('companies.add') }}
        <div id="main" class="container">
            <form method="POST" action="{{route('companies.update',$company->id)}}" accept-charset="UTF-8">
                @csrf
                <div class="row">
                    <div class="col-md-12 ">
                        <div class="main-form content-page">
                            <div class="form-body">
                                <div class="form-group row ">
                                    <div class="col-2">
                                        <label for="name" class="text-title-field control-label required">
                                            {{trans('layout.name')}}</label>
                                    </div>
                                    <div class="col-10">
                                        <input class="form-control @error('name') is-invalid @enderror"
                                         name="name" type="text" id="first_name" value=" {{old('name',$company->name)}}">
                                        @error('name')
                                        <span class="text-danger">{{ $message }}</span>
                                        @enderror
                                    </div>

                                </div>
                                <div class="form-group row">
                                    <div class="col-2">
                                        <label for="name" class="text-title-field control-label ">{{trans('layout.image')}}</label>
                                    </div>
                                    <!-- Button trigger modal -->
                                    <div class="col-10">
                                        <div class="image-box image">
                                            <input type="hidden" name="image" value="{{old('image',$company->image)}}"
                                                   class="image-data">
                                            <div class="preview-image-wrapper " style="">
                                                <img src="{{ $company->image? url_storage($company->image):asset('images/placeholder.png')}}"
                                                    class="preview_image" width="150">
                                                <a class="btn_remove_image" title="Remove image">
                                                    <i class="fa fa-times"></i>
                                                </a>
                                            </div>
                                            <div class="image-box-actions">
                                                <a href="#" class="btn_gallery" data-result="image"
                                                   data-bs-toggle="modal"
                                                   data-bs-target="#exampleModal">
                                                    {{trans('layout.choose_image')}}
                                                </a>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="clearfix"></div>
                            </div>
                            <div class="widget meta-boxes d-flex justify-content-center">
                                <div class="widget-body">
                                    <div class="btn-set">
                                        <a  href="{{route('companies.index')}}" class="float-left btn btn-warning mr-5"> {{trans('layout.cancel')}}</a>
                                        <button type="submit" name="submit" value="save" class="btn btn-info">
                                            <i class="fa fa-save"></i> {{trans('layout.update')}}
                                        </button>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </form>
        </div>
    </div>
    @include('partials.media')

@stop