routes/web.php
<?php

use App\Http\Controllers\AccessoryController;
use App\Http\Controllers\ActiveLogController;
use App\Http\Controllers\AssetController;
use App\Http\Controllers\AssetModelController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ComponentController;
use App\Http\Controllers\CustomFieldController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\LicenseController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\TableController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MediaController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('dashboard',[DashboardController::class,'index'])->name('dashboard.index');
Route::get('/',[DashboardController::class,'index']);

Route::get('/medias',[MediaController::class,'index'])->name('medias.index');
Route::get('get-data/medias/{id}',[MediaController::class,'getData'])->name('medias.data');
Route::post('post-data/medias/{id}',[MediaController::class,'uploadFile'])->name('medias.upload');
Route::post('medias-folder/store',[MediaController::class,'storeFolder'])->name('medias.folder.store');
Route::post('/medias-rename/update',[MediaController::class,'renameMedia'])->name('medias.rename');
Route::post('/medias-move/trash',[MediaController::class,'moveTrashMedia'])->name('medias.move.trash');
Route::get('/medias/download/{id}',[MediaController::class,'downloadMedia'])->name('medias.download');
Route::post('/medias/delete',[MediaController::class,'deleteMedia'])->name('medias.delete');
Route::post('/medias/restore',[MediaController::class,'restoreMedia'])->name('medias.restore');


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group( ['prefix'=>'users','as'=>'users.'],function () {
    Route::get('/',[UserController::class,'index'])->name('index');
    Route::get('/list/{trash}',[UserController::class,'index'])->name('trash');
    Route::get('/create',[UserController::class,'create'])->name('create');
    Route::post('/store',[UserController::class,'store'])->name('store');
    Route::get('/edit/{id}',[UserController::class,'edit'])->name('edit');
    Route::post('/update/{id}',[UserController::class,'update'])->name('update');
    Route::get('/clone/{id}',[UserController::class,'clone'])->name('clone');

    Route::delete('/deletes',[UserController::class,'deletes'])->name('deletes');
    Route::delete('/deleted/{id}',[UserController::class,'deleted'])->name('deleted');
    Route::delete('/empty-trash',[UserController::class,'emptyAllTrash'])->name('empty_trash');
    Route::get('/restore/{id}',[UserController::class,'restore'])->name('restore');
    Route::delete('/destroy/{id}',[UserController::class,'destroy'])->name('destroy');
    Route::get('{id}',[UserController::class,'show'])->name('show');
    Route::get('accessories/{id}',[UserController::class,'accessory'])->name('accessories');
    Route::get('assets/{id}',[UserController::class,'asset'])->name('assets');
});

Route::group( ['prefix'=>'companies','as'=>'companies.'],function () {
    Route::prefix('companies')->group(function () {
        Route::get('/',[CompanyController::class,'index'])->name('index');
        Route::get('/create',[CompanyController::class,'create'])->name('create');
        Route::post('/store',[CompanyController::class,'store'])->name('store');
        Route::get('/edit/{id}',[CompanyController::class,'edit'])->name('edit');
        Route::post('/update/{id}',[CompanyController::class,'update'])->name('update');
        Route::delete('/deletes/{id}',[CompanyController::class,'destroy'])->name('destroy');
    });
});
Route::prefix('departments')->group(function () {
    Route::get('/',[DepartmentController::class,'index'])->name('departments.index');
    Route::get('/create',[DepartmentController::class,'create'])->name('departments.create');
    Route::post('/store',[DepartmentController::class,'store'])->name('departments.store');
    Route::get('/edit/{id}',[DepartmentController::class,'edit'])->name('departments.edit');
    Route::post('/update/{id}',[DepartmentController::class,'update'])->name('departments.update');
    Route::delete('/deletes/{id}',[DepartmentController::class,'destroy'])->name('departments.destroy');

});

Route::prefix('categories')->group(function () {
    Route::get('/',[CategoryController::class,'index'])->name('categories.index');
    Route::get('/create',[CategoryController::class,'create'])->name('categories.create');
    Route::post('/store',[CategoryController::class,'store'])->name('categories.store');
    Route::get('/edit/{id}',[CategoryController::class,'edit'])->name('categories.edit');
    Route::post('/update/{id}',[CategoryController::class,'update'])->name('categories.update');
    Route::delete('/deletes/{id}',[CategoryController::class,'destroy'])->name('categories.destroy');
    Route::get('{id}',[CategoryController::class,'show'])->name('categories.show');
});
Route::prefix('locations')->group(function () {
    Route::get('/',[LocationController::class,'index'])->name('locations.index');
    Route::get('/create',[LocationController::class,'create'])->name('locations.create');
    Route::post('/store',[LocationController::class,'store'])->name('locations.store');
    Route::get('/edit/{id}',[LocationController::class,'edit'])->name('locations.edit');
    Route::post('/update/{id}',[LocationController::class,'update'])->name('locations.update');
    Route::delete('/deletes/{id}',[LocationController::class,'destroy'])->name('locations.destroy');
    Route::get('{id}',[LocationController::class,'show'])->name('locations.show');
});

Route::prefix('components')->group(function () {
    Route::get('/',[ComponentController::class,'index'])->name('components.index');
    Route::get('/create',[ComponentController::class,'create'])->name('components.create');
    Route::post('/store',[ComponentController::class,'store'])->name('components.store');
    Route::get('/edit/{id}',[ComponentController::class,'edit'])->name('components.edit');
    Route::post('/update/{id}',[ComponentController::class,'update'])->name('components.update');
    Route::delete('/deletes/{id}',[ComponentController::class,'destroy'])->name('components.destroy');
    Route::get('{id}',[ComponentController::class,'show'])->name('components.show');
    Route::post('{id}/checkout',[ComponentController::class,'checkout'])->name('components.checkout');
    Route::post('{id}/checkin',[ComponentController::class,'checkin'])->name('components.checkin');
    Route::get('/{id}/qr-code-download',[ComponentController::class,'qrCodeDownload'])->name('components.qr.download');
});

Route::prefix('licenses')->group(function () {
    Route::get('/',[LicenseController::class,'index'])->name('licenses.index');
    Route::get('/list/{trash}',[LicenseController::class,'index'])->name('licenses.trash');
    Route::get('/create',[LicenseController::class,'create'])->name('licenses.create');
    Route::post('/store',[LicenseController::class,'store'])->name('licenses.store');
    Route::get('/edit/{id}',[LicenseController::class,'edit'])->name('licenses.edit');
    Route::post('/update/{id}',[LicenseController::class,'update'])->name('licenses.update');
    Route::get('/clone/{id}',[LicenseController::class,'clone'])->name('licenses.clone');
    Route::delete('/deletes/{id}',[LicenseController::class,'destroy'])->name('licenses.destroy');

    Route::post('{id}/checkout/{seat_id?}',[LicenseController::class,'checkout'])->name('licenses.checkout');
    Route::post('{id}/checkin/{seat_id?}',[LicenseController::class,'checkin'])->name('licenses.checkin');
    Route::get('/{id}',[LicenseController::class,'show'])->name('licenses.show');
    Route::get('/{id}/qr-code-download',[LicenseController::class,'qrCodeDownload'])->name('licenses.qr.download');
});

Route::prefix('accessories')->group(function () {
    Route::get('/',[AccessoryController::class,'index'])->name('accessories.index');
    Route::get('/list/{trash}',[AccessoryController::class,'index'])->name('accessories.trash');
    Route::get('/create',[AccessoryController::class,'create'])->name('accessories.create');
    Route::post('/store',[AccessoryController::class,'store'])->name('accessories.store');
    Route::get('/edit/{id}',[AccessoryController::class,'edit'])->name('accessories.edit');
    Route::post('/update/{id}',[AccessoryController::class,'update'])->name('accessories.update');
    Route::get('/clone/{id}',[AccessoryController::class,'clone'])->name('accessories.clone');

    Route::delete('/deletes',[AccessoryController::class,'deletes'])->name('accessories.deletes');
    Route::delete('/deleted/{id}',[AccessoryController::class,'deleted'])->name('accessories.deleted');
    Route::delete('/empty-trash',[AccessoryController::class,'emptyAllTrash'])->name('accessories.empty_trash');
    Route::get('/restore/{id}',[AccessoryController::class,'restore'])->name('accessories.restore');
    Route::delete('/destroy/{id}',[AccessoryController::class,'destroy'])->name('accessories.destroy');
    Route::post('{id}/checkout/{seat_id?}',[AccessoryController::class,'checkout'])->name('accessories.checkout');
    Route::post('{id}/checkin/{seat_id?}',[AccessoryController::class,'checkin'])->name('accessories.checkin');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $table='categories';
    protected $fillable=['name','image','user_id','eula_text','use_default_eula','require_acceptance','checkin_email','category_type'];

    public function isDeletable()
    {
        if ($this->itemCount() == 0) {
            return false;
        }
        return true;
    }
    public function itemCount()
    {
        switch ($this->category_type) {
            case 'asset':
                return $this->assets()->count();
            case 'accessory':
                return $this->accessories()->count();
            case 'component':
                return $this->components()->count();
            case 'consumable':
                return $this->consumables()->count();
            case 'license':
                return $this->licenses()->count();
        }
        return '0';
    }
    public function assets()
    {
        return $this->hasManyThrough(Asset::class, '\App\Models\AssetModel', 'category_id', 'model_id');
    }
    public function models()
    {
        return $this->hasMany(AssetModel::class, 'category_id');
    }
    public function components()
    {
        return $this->hasMany(Component::class);
    }
    public function licenses()
    {
        return $this->hasMany(License::class);
    }
    public function accessories()
    {
        return $this->hasMany(Accessory::class);
    }
}

app/Models/LicenseSeat.php
<?php
namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class LicenseSeat extends Model
{

    use SoftDeletes;


    protected $presenter = 'App\Presenters\LicenseSeatPresenter';


    protected $dates = ['deleted_at'];
    protected $guarded = 'id';
    protected $table = 'license_seats';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'assigned_to',
        'asset_id',
        'user_id'
    ];



    public function getCompanyableParents()
    {
        return ['asset', 'license'];
    }

    /**
     * Determine whether the user should be required to accept the license
     *
     * @author A. Gianotto <snipe@snipe.net>
     * @since [v4.0]
     * @return boolean
     */
    public function requireAcceptance()
    {
        return $this->license->category->require_acceptance;
    }

    public function getEula() {
        return $this->license->getEula();
    }

    /**
     * Establishes the seat -> license relationship
     *
     * @author A. Gianotto <snipe@snipe.net>
     * @since [v1.0]
     * @return \Illuminate\Database\Eloquent\Relations\Relation
     */
    public function license()
    {
        return $this->belongsTo(License::class, 'license_id');
    }

    /**
     * Establishes the seat -> assignee relationship
     *
     * @author A. Gianotto <snipe@snipe.net>
     * @since [v1.0]
     * @return \Illuminate\Database\Eloquent\Relations\Relation
     */
    public function user()
    {
        return $this->belongsTo(User::class,'assigned_to')->withTrashed();
    }

    /**
     * Establishes the seat -> asset relationship
     *
     * @author A. Gianotto <snipe@snipe.net>
     * @since [v4.0]
     * @return \Illuminate\Database\Eloquent\Relations\Relation
     */
    public function asset()
    {
        return $this->belongsTo(Asset::class, 'asset_id')->withTrashed();
    }

    /**
     * Determines the assigned seat's location based on user
     * or asset its assigned to
     *
     * @author A. Gianotto <snipe@snipe.net>
     * @since [v4.0]
     * @return string
     */
    public function location()
    {
        if (($this->user) && ($this->user->location)) {
            return $this->user->location;

        } elseif (($this->asset) && ($this->asset->location)) {
            return $this->asset->location;
        }

        return false;

    }

    /**
     * Query builder scope to order on department
     *
     * @param  \Illuminate\Database\Query\Builder  $query  Query builder instance
     * @param  text                              $order         Order
     *
     * @return \Illuminate\Database\Query\Builder          Modified query builder
     */
    public function scopeOrderDepartments($query, $order)
    {
        return $query->leftJoin('users as license_seat_users',  'license_seats.assigned_to', '=', 'license_seat_users.id')
            ->leftJoin('departments as license_user_dept',  'license_user_dept.id', '=', 'license_seat_users.department_id')
            ->orderBy('license_user_dept.name', $order);
    }




}

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
    public function index(Request $request)
    {

        if ($request->ajax()) {

            $term = trim($request->term);
            $posts = DB::table('categories')
                ->select('id', 'name as text','category_type')
                ->where('category_type',$request->category_type)
                ->where('name', 'LIKE', '%' . $term . '%')
                ->orderBy('name', 'asc')->simplePaginate(2);

            $morePages = true;
            if (empty($posts->nextPageUrl())) {
                $morePages = false;
            }
            $results = array(
                "results" => $posts->items(),
                "pagination" => array(
                    "more" => $morePages
                )
            );

            return response()->json($results);
        }

    }
}

resources/views/categories/add.blade.php
@extends('layouts.app')
@section('content')
    <div class=" rv-media-integrate-wrapper ">
        {{ Breadcrumbs::render('categories.add') }}
        <div id="main" class="container">
            <form method="POST" action="{{route( 'categories.store')}}" accept-charset="UTF-8">
                @csrf
                <div class="row">
                    <div class="col-md-12 ">
                        <div class="main-form content-page">
                            <div class="form-body">
                                <div class="form-group ">
                                    <div class="row">
                                        <div class="col-md-2 text-right">
                                            <label for="name" class="text-title-field control-label required">
                                                {{trans('layout.name')}}</label>
                                        </div>
                                        <div class="col-md-10">
                                            <input class="form-control @error('name') is-invalid @enderror" name="name"
                                                   type="text" id="first_name" value="{{old('name')}}">
                                            @error('name')
                                            <span class="text-danger">{{ $message }}</span>
                                            @enderror
                                        </div>
                                    </div>

                                </div>
                                <div class="form-group ">
                                    <div class="d-flex ">
                                        <div class="col-md-2 text-right">
                                            <label for="category_type" class="text-title-field control-label required">
                                                {{trans('layout.type')}}
                                            </label>
                                        </div>
                                        <select class="form-control" name="category_type">
                                            <option value="asset">Asset</option>
                                            <option value="license">License</option>
                                            <option value="component">Component</option>
                                            <option value="accessory">Accessories</option>
                                        </select>
                                    </div>

                                </div>
                                <div class="form-group ">
                                    <div class="d-flex ">
                                        <div class="col-md-2 text-right">
                                            <label for="eula_text" class="text-title-field control-label ">
                                              {{trans('layout.category.eula')}}</label>
                                        </div>
                                        <div  class="col-md-10 text-right">
                                            <textarea class="form-control @error('eula_text') is-invalid @enderror"
                                                      name="eula_text" type="text" id="eula_text"></textarea>
                                        </div>
                                    </div>


                                    <div class="form-group ">
                                        <div class="d-flex">
                                            <div class="col-md-2 text-right">
                                                <label for="name" class="text-title-field control-label ">{{trans('layout.image')}}</label>
                                            </div>
                                            <!-- Button trigger modal -->
                                            <div class="image-box image">
                                                <input type="hidden" name="image" value="{{old('image')}}"
                                                       class="image-data">
                                                <div class="preview-image-wrapper " style="">
                                                    <img src="{{asset('images/placeholder.png')}}" alt="Preview image"
                                                         class="preview_image" width="150">
                                                    <a class="btn_remove_image" title="Remove image">
                                                        <i class="fa fa-times"></i>
                                                    </a>
                                                </div>
                                                <div class="image-box-actions">
                                                    <a href="#" class="btn_gallery" data-result="image"
                                                       data-bs-toggle="modal"
                                                       data-bs-target="#exampleModal">
                                                        {{trans('layout.choose_image')}}
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="widget meta-boxes d-flex justify-content-center">
                                    <div class="widget-body">
                                        <div class="btn-set">
                                            <a href="{{route('categories.index')}}"
                                               class="float-left btn btn-warning mr-5">{{trans('layout.cancel')}}</a>
                                            <button type="submit" name="submit" value="save" class="btn btn-info">
                                                <i class="fa fa-save"></i> {{trans('layout.update')}}
                                            </button>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </form>
        </div>
    </div>
    @include('partials.media')
@stop

resources/views/categories/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class=" rv-media-integrate-wrapper ">
        {{ Breadcrumbs::render('categories.edit',$category->id) }}
        <div id="main" class="container">
            <form method="POST" action="{{route( 'categories.update',$category->id)}}" accept-charset="UTF-8">
                @csrf
                <div class="row">
                    <div class="col-md-12 ">
                        <div class="main-form content-page">
                            <div class="form-body">
                                <div class="form-group ">
                                    <div class="row ">
                                        <div class="col-md-2 text-right">
                                            <label for="name" class="text-title-field control-label required">
                                              {{trans('layout.name')}}</label>
                                        </div>
                                        <div class="col-10">
                                            <input class="form-control @error('name') is-invalid @enderror"
                                               name="name" type="text" id="name" value="{{old('name',$category->name)}}">
                                            @error('name')
                                            <span class="text-danger">{{ $message }}</span>
                                            @enderror
                                        </div>
                                    </div>

                                </div>
                                <div class="form-group ">
                                    <div class="d-flex ">
                                        <div class="col-md-2 text-right">
                                            <label for="category_type" class="text-title-field control-label ">
                                                {{trans('layout.type')}}
                                            </label>
                                        </div>
                                        <select class="form-control" name="category_type" disabled>
                                            <option value="asset" {{$category->category_type=='asset'?'selected':''}}>Asset</option>
                                            <option value="license" {{$category->category_type=='license'?'selected':''}}>License</option>
                                            <option value="component" {{$category->category_type=='component'?'selected':''}}>Component</option>
                                            <option value="accessory"{{$category->category_type=='accessory' ?'selected':''}}>Accessories</option>
                                        </select>

                                    </div>

                                </div>
                                <div class="form-group ">
                                    <div class="d-flex ">
                                        <div class="col-md-2 text-right">
                                            <label for="eula_text" class="text-title-field control-label ">
                                                {{trans('layout.category.eula')}}</label>
                                        </div>

                                        <div class="col-10">
                                            <textarea class="form-control" name="eula_text" type="text" id="eula_text">
                                            </textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <div class="d-flex">
                                        <div class="col-md-2 text-right">
                                            <label for="name" class="text-title-field control-label "> {{trans('layout.image')}}</label>
                                        </div>
                                        <!-- Button trigger modal -->
                                        <div class="image-box image">
                                            <input type="hidden" name="image" value="{{old('image',$category->image)}}"
                                                   class="image-data">
                                            <div class="preview-image-wrapper " style="">
                                                <img
                                                    src="{{ $category->image? url_storage($category->image):asset('images/placeholder.png')}}"
                                                    alt="Preview image" class="preview_image" width="150">
                                                <a class="btn_remove_image" title="Remove image">
                                                    <i class="fa fa-times"></i>
                                                </a>
                                            </div>
                                            <div class="image-box-actions">
                                                <a href="#" class="btn_gallery" data-result="image"
                                                   data-bs-toggle="modal"
                                                   data-bs-target="#exampleModal">
                                                    {{trans('layout.choose_image')}}
                                                </a>
                                            </div>
                                        </div>

                                    </div>


                                </div>

                                <div class="clearfix"></div>
                            </div>
                            <div class="widget meta-boxes d-flex justify-content-center">
                                <div class="widget-body">
                                    <div class="btn-set">
                                        <a  href="{{route('categories.index')}}" class="float-left btn btn-warning mr-5"> {{trans('layout.cancel')}}</a>
                                        <button type="submit" name="submit" value="save" class="btn btn-info">
                                            <i class="fa fa-save"></i>  {{trans('layout.update')}}
                                        </button>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
    @include('partials.media')
@stop